FROM node:14.11.0-alpine3.12 AS build-env
WORKDIR /usr/src/app
COPY mountains.proto ./
COPY client/package*.json ./
COPY client/src/ ./
RUN ["npm", "install"]

FROM node:14.11.0-alpine3.12
COPY --from=build-env /app /app
WORKDIR /app
EXPOSE 3000
CMD ["start"]
