FROM node:14 AS build-env
ADD client/ /app
COPY mountains.proto /app
COPY package.json /
WORKDIR /app

RUN yarn --prod

FROM gcr.io/distroless/nodejs:14
COPY --from=build-env /app /app
WORKDIR /app
EXPOSE 3000
CMD ["index"]
