FROM node:14.11.0-alpine3.12 AS build-env
ADD client/ /app
COPY mountains.proto /app
COPY package.json /
WORKDIR /app

RUN yarn --prod

FROM node:14.11.0-alpine3.12
COPY --from=build-env /app /app
WORKDIR /app
EXPOSE 3000
CMD ["start"]
