FROM node:14.11.0-alpine3.12 AS build
WORKDIR /usr/src/app
COPY mountains.proto ./
COPY client/package*.json ./
COPY client/src/ ./
RUN ["npm", "install"]

FROM node:14.11.0-alpine3.12
WORKDIR /app
COPY --from=build /usr/src/app ./
EXPOSE 3000
CMD ["start"]
