FROM node:14 AS build-env
WORKDIR /usr/src/app
COPY mountains.proto ./
COPY server/package*.json ./
COPY server/src/ ./
RUN ["npm", "install"]

FROM gcr.io/distroless/nodejs:14
COPY --from=build-env /app /app
WORKDIR /app
EXPOSE 8321
CMD ["start"]
